import Header from "./_components/Header";

export const metadata = {
  title: "Melo",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
